<a href="https://colab.research.google.com/github/PurraSujay/MachineLearning-Projects/blob/main/Navi_bayes_Emial_spam_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Navi Bayes E-mail Spam Filter**

In [11]:

import pandas as pd

In [14]:
df = pd.read_csv('spam.csv',encoding='latin-1')

df.head()

v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [16]:
df.groupby('v1').describe()

v2         ... Unnamed: 4     
     count unique  ...        top freq
v1                 ...                
ham   4825   4516  ...    GNT:-)"    2
spam   747    653  ...        NaN  NaN

[2 rows x 16 columns]

In [17]:
df['spam']=df['v1'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

v1                                                 v2  ... Unnamed: 4 spam
0   ham  Go until jurong point, crazy.. Available only ...  ...        NaN    0
1   ham                      Ok lar... Joking wif u oni...  ...        NaN    0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...  ...        NaN    1
3   ham  U dun say so early hor... U c already then say...  ...        NaN    0
4   ham  Nah I don't think he goes to usf, he lives aro...  ...        NaN    0

[5 rows x 6 columns]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.v2,df.spam)

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [22]:

X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9885139985642498


Sklearn Pipeline

In [23]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [24]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [25]:

clf.score(X_test,y_test)

0.9885139985642498

In [26]:

clf.predict(emails)

array([0, 1])